### ISSUE TITLE
trakt: Retry search without `year` if it yielded no results the first time

### ISSUE THREAD

**Issue by JRFarmer** [iamkroot/trakt-scrobbler#129] opened 2021-07-08 23:19 UTC
Playing Sneaky Pete episodes on Plex, I notice these episodes do not scrobble. I checked the log, it's due to an invalid Trakt id. Maybe caused by year mismatch. Plex metadata has Sneaky Pete year as 2017, while Trakt has the year as 2015.

Running trakt-scrobbler on Ubuntu 20.04.2
Python 3.8.10
Plex Server version 1.23.2.4656
Roku Plex client

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
2021-07-06 20:23:14,748 - DEBUG - plex - monitor - action=scrobble
2021-07-06 20:23:14,748 - DEBUG - plex - monitor - {'state': 2, 'progress': 0.0, 'media_info': {'type': 'episode', 'title': 'Sneaky Pete', 'season': 1, 'episode': 1, 'year': 2017}, 'updated_at': 1625617394.748422}
2021-07-06 20:23:14,748 - DEBUG - scrobbler - scrobbler - Scrobbling start at 0.00% for Sneaky Pete
2021-07-06 20:23:14,749 - DEBUG - scrobbler - trakt_interface - Searching trakt: Title: "Sneaky Pete", Year: 2017
2021-07-06 20:23:14,924 - WARNING - scrobbler - trakt_interface - Trakt search yielded no results for the show, Sneaky Pete, Year: 2017
2021-07-06 20:23:14,926 - DEBUG - scrobbler - trakt_interface - Trakt ID: -1
2021-07-06 20:23:14,927 - WARNING - scrobbler - trakt_interface - Invalid trakt id for Sneaky Pete
2021-07-06 20:23:14,927 - WARNING - scrobbler - scrobbler - Scrobble unsuccessful.
```
</p>
</details>

**Comment by iamkroot** [comment] 2021-07-09 05:21
This is not a bug, since there's nothing much our app can do in this case. We get whatever metadata (like name, year, episode, etc.) Plex provides, and use it to search Trakt. But if they don't match, this is the fault of either Plex or Trakt (or both), not of this scrobbler. This app currently tries no shenanigans to correct the metadata, although #95 may change that if/when it is implemented.

Fortunately for you, there _is_ a way for you to get this to work. You can manually specify the trakt ID inside `trakt_cache.json` instead of the `-1` you see in the log.
1. Open the file in a text editor. It will be located alongside the log file.
2. Change the value for `Sneaky Pete2017` from `-1` to `101657`.
3. `trakts start --restart`

The `trakts` command to fetch the Trakt ID of a show/movie will be released in the next version of this scrobbler.

**Comment by JRFarmer** [comment] 2021-07-09 12:34
@iamkroot Thanks for the detailed response. I see your point about not trying any shenanigans to correct metadata.

When this happens to me again in the future, how can I manually fetch the correct Trakt ID of the offending show?

I think you're right to close this 'bug' but I think there's room for an enhancement. This year mismatch is a problem that is likely to occur frequently. Movies are often listed with different years between Plex, IMDb, TVDB and Trakt. Sometimes they list the year the movie debuts at Cannes, sometimes they list the year the movie was released in US theaters.

I worked-around this problem by adding 'year=None' near the top of get_trakt_id() in trakt_interface.py. With the year omitted, the search was successful and the ID was good. Maybe a 'retry' search that omits the year could be added if the year-specific search gives no result?

**Comment by iamkroot** [comment] 2021-07-09 13:39
> When this happens to me again in the future, how can I manually fetch the correct Trakt ID of the offending show?

As I mentioned, the next release will add a `trakts lookup` command to enable exactly this. See https://github.com/iamkroot/trakt-scrobbler/issues/95#issuecomment-751437087


> Movies are often listed with different years between Plex, IMDb, TVDB and Trakt.

When I originally added the forced filtering of results by year, I was worried about this. But the benefits of filtering by year (in case of multiple releases with the same title) outweighed the costs of being too strict (due to having a wrong year in the metadata).


> Maybe a 'retry' search that omits the year could be added if the year-specific search gives no result?

That actually does seem like a very plausible thing to do in this scenario. The only negative side-effect I see from doing this, is that we might scrobble the wrong media in case the metadata extraction was botched (eg: wrong title AND wrong year), whereas filtering by year would've prevented that. But I think the chances of this happening are pretty slim, even slimmer than having mismatched years in Plex and Trakt.

I will probably go ahead and implement this when I get some time. Thanks a lot for suggesting the enhancement.

**Comment by JRFarmer** [comment] 2021-07-09 16:40
> I will probably go ahead and implement this when I get some time.

If you don't mind, I'll take a stab at it this weekend and send you a PR.

**Comment by iamkroot** [comment] 2021-07-09 16:55
> If you don't mind, I'll take a stab at it this weekend and send you a PR.

Of course! Do go ahead. Please take care to follow the https://github.com/iamkroot/trakt-scrobbler/blob/master/CONTRIBUTING.md guidelines btw.

**Closed** 2021-07-11 05:54 UTC
Labels: enhancement
