### ISSUE TITLE
[BUG] Config.toml doesn't accept "é" character and probably others as well

### ISSUE THREAD

**Issue by fabiorfreitas** [iamkroot/trakt-scrobbler#30] opened 2019-10-22 11:20 UTC
**Describe the bug**
Ok, below is my current working setup. I don't have all the log files, but I did lots of testing and I'm pretty sure I've isolated this problem: whenever I tried to whitelist a path in config.toml, if it included the "é" character, the log would say that the file was not whitelisted.

My final test was simply changing "C:/Users/Fabio/Videos/Séries/" in the whitelist to "C:/Users/Fabio/Videos/" (all testing was done by reinstalling everything from scratch, no leftovers), this simple change made everything work as intended (thanks, btw). I'm guessing somewhere in the process this character breaks it.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Python Version: 3.7.4
 - Player: MPC-HC
 - Player Version: 1.8.8

**Config.toml**
<details><summary>Click to see log contents</summary>
<p>

```
[general]
enable_notifs = true

[fileinfo]
whitelist = [
	"C:/Users/Fabio/Videos/"
]

[players]
monitored = ['mpchc', 'mpv']  # players to be monitored. Allowed: 'mpcbe', 'mpchc', 'mpv', 'vlc'
skip_interval = 5  # min percent jump to consider for scrobbling to trakt

[players.mpcbe]  # enable web interface from options
ip = "localhost"
port = "13579"  # from Options -> Player -> Web Interface -> Listen on port  (ensure it is ticked) 
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.

[players.mpchc]  # enable web interface from options
ip = "localhost"
port = "13579"  # if both mpchc and mpcbe are to be monitored, then ensure that their ports are different
poll_interval = 10  # in seconds

[players.vlc]  # enable web interface from options
ip = "localhost"
port = "8080"  # from Preferences -> All -> Input/Codecs -> HTTP Server Port
password = "password"  # from Preferences -> All -> Interface -> Main Interfaces -> Lua -> Lua HTTP Password
poll_interval = 10  # in seconds. How frequently the monitor should check for player update.

[players.mpv]  # enable the JSON IPC server. Either via cmd line arg (eg: --input-ipc-server=\\.\pipe\mpvpipe), or in mpv.conf file
ipc_path = '\\.\pipe\mpvpipe'  # windows (single quotes are important)
# ipc_path = "/tmp/mpvsocket"  # unix

```
</p>
</details>

**Comment by iamkroot** [comment] 2019-10-24 07:40
I can't reproduce this on my system. This is what I get when running the whitelisting logic manually from a Python REPL.
```python
>>> from pathlib import Path
>>> wl = Path("C:/Users/Fabio/Videos/Séries/")  # folder to be whitelisted
>>> fp = Path("C:/Users/Fabio/Videos/Séries/a/b.mkv")  # media file
>>> parents = list(fp.absolute().resolve().parents)
>>> parents  # the given whitelist folder should be a parent of the media file
[WindowsPath('C:/Users/Fabio/Videos/Séries/a'), WindowsPath('C:/Users/Fabio/Videos/Séries'), WindowsPath('C:/Users/Fabio/Videos'), WindowsPath('C:/Users/Fabio'), WindowsPath('C:/Users'), WindowsPath('C:/')]
>>> wl in parents
True  # allow through whitelist
```
The problem might be somewhere else. Could you send the log file, so that it can be pinpointed?

**Comment by iamkroot** [comment] 2020-01-16 11:59
@fabiorfreitas I was able to reproduce the error on a clean windows install and have pushed a fix in the latest commit. Give it a try!

**Closed** 2020-01-16 11:58 UTC
