### ISSUE TITLE
Which command to restart the scrobbler, after the error: 503 "Server Error"?

### ISSUE THREAD

**Issue by bulletproof2k** [iamkroot/trakt-scrobbler#218] opened 2022-10-18 05:59 UTC
Often, the service does not have time until the Plex Server opens and issues a 503 error. I just don't know which command to restart the scrobbler.

**Comment by iamkroot** [comment] 2022-10-18 16:07
It should be as simple as `trakts start --restart`. (See [trakts CLI Reference](https://github.com/iamkroot/trakt-scrobbler/wiki/trakts-CLI-Reference))

But you shouldn't need to do that manually. Could you please share the logs (`trakts log open`) with some error tracebacks?

**Comment by bulletproof2k** [comment] 2022-10-18 16:19
This does not always happen. It's probably a little silly, but you have to restart the computer in order for the service to work again.

**Comment by iamkroot** [comment] 2022-10-22 12:28
> have to restart the computer in order for the service to work again

Maybe the bug is in the Plex server instead?
From the logs, I don't see any failures/crashes on our end.

**Comment by iamkroot** [comment] 2022-10-22 12:29
Duplicate of #211

**Closed by iamkroot** 2022-10-22 12:29 UTC
Labels: monitor
