### ISSUE TITLE
[BUG] Beta-1.3.0b2 on „trakts start“ OR "trakts status"

### ISSUE THREAD

**Issue by frykauf** [iamkroot/trakt-scrobbler#134] opened 2021-07-22 17:39 UTC
**Describe the bug**

Bug on „trakts start“ or „trakts status“.
Otherwise trakt-scrobbler seems to have launched, running & trakts config also works.

**Desktop (please complete the following information):**
 - macOS 11.4 (20F71)
 - Python Version: 3.9.5
 - Player and Version: IINA 1.2.0

**To Reproduce**

1. „trakts start“ OR „trakts status"

**Log file no.1**

19:29 $ trakts start

  CalledProcessError

  Command '['launchctl', 'start', 'com.iamkroot.trakt-scrobbler']' returned non-zero exit status 3.

  at /usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py:373 in check_call
       369│     if retcode:
       370│         cmd = kwargs.get("args")
       371│         if cmd is None:
       372│             cmd = popenargs[0]
    →  373│         raise CalledProcessError(retcode, cmd)
       374│     return 0
       375│ 
       376│ 
       377│ def check_output(*popenargs, timeout=None, **kwargs):

**Log file no.2**

trakts status
Could not find service "com.iamkroot.trakt-scrobbler" in domain for port

  CalledProcessError

  Command '['launchctl', 'list', 'com.iamkroot.trakt-scrobbler']' returned non-zero exit status 113.

  at /usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│ 
       532│ 

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
(replace this line) *PASTE LOG FILE CONTENTS HERE* Command: "trakts log open" or "trakts log path"
```
</p>
</details>

**Comment by iamkroot** [comment] 2021-07-23 06:21
Looks like a duplicate of #83 
I would really like to get to the bottom of this. If you are willing to spend some time to assist me, let me know

**Closed by iamkroot** 2021-07-23 06:21 UTC
