### ISSUE TITLE
[BUG] Installation failed because of dbus-python

### ISSUE THREAD

**Issue by achessoux** [iamkroot/trakt-scrobbler#21] opened 2019-07-25 21:48 UTC
**Describe the bug**
dbus-python is not seen by virtualenv wheras it is installed and its installation in the venv fails.
_Thanks in advance for investigation and your help.
Thanks for the already done work! :)_

**Desktop (please complete the following information):**
 - OS: Ubuntu Disco
 - Python Version: 3.7.3
 - Player: N/A
 - Player Version: N/A
 -dbus-python Version: python3-dbus (1.2.8-3)

**To Reproduce**
Installation of trakt-scrobbler on Ubuntu.
See error in log file

**Log file**
<details><summary>Click to see log contents</summary>
<p>
aymeric@ricoh-xps:/home/Public/trakt-scrobbler-master$ ./scripts/linux-install-service.sh 
Checking pipenv install.

Checking config file
config.toml already exists in /home/aymeric/.config/trakt-scrobbler/.
Please ensure that it matches sample_config.toml, or the app may crash unexpectedly.

Installing to /home/aymeric/.local/trakt-scrobbler/
Installing dependencies from Pipfile.lock (b0e854)…
An error occurred while installing dbus-python==1.2.8; sys_platform != 'win32'! Will try again.
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring win10toast: markers 'sys_platform == "win32"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 16/16 — 00:00:08
Installing initially–failed dependencies…
Collecting dbus-python==1.2.8 ▉▉▉▉▉▉▉ 0/1 — 00:00:00
  Using cached https://files.pythonhosted.org/packages/3f/e7/4edb582d1ffd5ac3c84188deea32e960b5c8c0fe1da56ce70224f85ce542/dbus-python-1.2.8.tar.gz

    ERROR: Command errored out with exit status 1:
     command: /home/aymeric/.local/share/virtualenvs/trakt-scrobbler-sC3BQFdg/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oowgpdhh/dbus-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oowgpdhh/dbus-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-oowgpdhh/dbus-python/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/aymeric/.local/share/virtualenvs/trakt-scrobbler-sC3BQFdg/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/aymeric/.local/share/virtualenvs/trakt-scrobbler-sC3BQFdg/lib/python3.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:01
Error while creating venv
</p>
</details>

**Comment by iamkroot** [comment] 2019-07-26 06:23
Seems to be a problem with you setuptools install. Try `apt install --reinstall python3-pkg-resources`

**Comment by achessoux** [comment] 2019-07-26 09:10
> Seems to be a problem with you setuptools install. Try `apt install --reinstall python3-pkg-resources`

It haven't changed anything...

**Comment by iamkroot** [comment] 2019-07-27 04:16
How about reinstalling setuptools too? `sudo apt install --reinstall python3-pkg-resources python3-setuptools`

**Comment by achessoux** [comment] 2019-07-27 10:47
Hello,
This does not change anything too. Same result.
Thanks for your help.

Le sam. 27 juil. 2019 à 06:16, Krut Patel <notifications@github.com> a
écrit :

**Comment by iamkroot** [comment] 2019-07-28 02:18
Have you run `apt install python3-dbus` from the install instructions?

**Comment by achessoux** [comment] 2019-07-28 06:16
Yes, I have also tried with --reinstall after.

Le dim. 28 juil. 2019 à 04:18, Krut Patel <notifications@github.com> a
écrit :

**Comment by iamkroot** [comment] 2019-08-01 15:59
I don't really know what is causing the error then :/

**Comment by pygospa** [comment] 2019-09-26 06:14
Hey @achessoux, 
not sure if this is related, but I got this error:

> An error occurred while installing dbus-python==1.2.8 ; sys_platform != 'win32' --hash=sha256:abf12bbb765e300bf8e2a1b2f32f85949eab06998dbda127952c31cb63957b6f! Will try again.
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment                                                        
Ignoring win10toast: markers 'sys_platform == "win32"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 16/16 — 00:00:08                                      
Installing initially failed dependencies…
(...)
returned non-zero exit status 1.", '  ----------------------------------------', '  ERROR: Failed building wheel for dbus-python', '    ERROR: Command errored out with exit status 1:', '

So I tried installing python-dbus manually, first by `apt install`:

> python3-dbus is already the newest version (1.2.6-1).

Then using pip3:

>   checking for DBUS... no
  configure: error: Package requirements (dbus-1 >= 1.8) were not met:
> 
>  No package 'dbus-1' found
>   Failed building wheel for dbus-python

Googling this error message, I found this solution:

> sudo apt install python3-xlib python3-pyinotify wmctrl

I believe you will probably only need the `python3-xlib`, but just in case I listed all the packages from that solution.

Good luck!

**Comment by tezgno** [comment] 2019-11-27 18:18
I am having the same problem with Ubuntu 18.04 LTS as well. In looking at the script, I believe the issue is that the LTS version of Ubuntu doesn't have the latest version of python. I'm going to build a separate VM that is running a newer version of Ubuntu to try it out. From what I can gather, it would appear as though this script is really designed for non-LTS versions of Linux.

**Comment by iamkroot** [comment] 2019-11-28 07:25
@tezgno that's not correct. I was running Ubuntu 18.04 while creating this app, as my daily OS. So there shouldn't be any problems due to the python versions. It could be that there's been an update to the dbus-python dependency, causing the problem. Thanks for your help in figuring out the cause, much appreciated :)

**Comment by tezgno** [comment] 2019-11-28 15:45
@iamkroot Thanks. While it does appear as though you developed it on 18.04, dbus-python did in fact update from 1.2.6-1 to 1.2.12, which is not available on the LTS version of 18.04. I'm going to try setting this up right now on the non-LTS version to see if my suspicion is correct. I'll report back with my findings.

**Comment by tezgno** [comment] 2019-11-28 17:15
@iamkroot Ok, after moving to 19.10, I was able to get past the dbus error so it's definitely an issue with the LTS version. However, I have now run into a new problem that was unexpected. I now get errors about org.freedesktop and notifications. Does your script have an expectation of there being a GUI? If so, then my entire problem not be 18.04 or any of that, but rather that this was developed on Ubuntu Desktop and I'm running Ubuntu server (no GUI). I have a Ubuntu Desktop VM. Going to switch over to that machine and give this a try to see if it works on the Ubuntu Desktop. If so, then my entire problem can be solved that way.

**Comment by iamkroot** [comment] 2019-11-28 17:24
@tezgno Thanks for taking the time to locate the bug!

> Does your script have an expectation of there being a GUI?

Well, yeah. The entire point of dbus is to be able to send notifications. So not having a GUI would cause an error. 

I've been mulling over the unreliability of dbus-python for quite some time now. I think it'd be simpler to just use `notify-send` from a subprocess and let that handle the dbus. Right now, on some rare occasions, the app does crash due to random dbus errors. I'll test that method and push the changes if its viable.

If you want a quick and dirty way to get the app running, here's what you can do:
1. Remove the dbus-python dep from Pipfile and Pipfile.lock (delete the lines) 
2. Set the `enable_notifs` parameter to `false` in your config file, and then run the install script.
This will cause the dependency to never be imported, and everything else will work normally. 

Again, thanks for your help!

**Comment by tezgno** [comment] 2019-11-28 20:54
@iamkroot Setting that value to false as well as removing those lines allowed for the software to be installed on 18.04 LTS and 19.10 Server builds. I was able to install on 19.10 desktop no modifications (other than pip3 being installed and some symlinks). It looks like if you can get around the use of dbus, the code would work on all of the Ubuntu builds (regardless of server, desktop, or LTS).

**Closed** 2019-11-29 06:06 UTC
Labels: help wanted

**Comment by iamkroot** [comment] 2019-11-29 06:07
@tezgno Updated the code and removed the dependency on dbus. Give it a try now. Do remember that you'll need `libnotify` installed on your system if you want to enable notifications.
