### ISSUE TITLE
[BUG] Stops working after not in use for some time

### ISSUE THREAD

**Issue by cyatek** [iamkroot/trakt-scrobbler#7] opened 2019-06-15 15:13 UTC
**Describe the bug**
If nothing in the whitelist folder is played for a ~day, the next day pythonw.exe will still be running but the script is dead.

**OS**: Windows 7

**Log file**
<details><summary>Click to see log contents</summary>
<p>

```
2019-06-14 12:31:03,614 - INFO - MainThread - scrobbler - Started scrobbler thread.
2019-06-14 12:31:03,614 - WARNING - MainThread - utils - data\watched_cache.json doesn't exist.
2019-06-14 12:31:03,616 - INFO - MainThread - monitor - Started monitor for mpchc
2019-06-14 12:31:04,624 - INFO - mpchc - monitor - Unable to connect to mpchc. Ensure that the web interface is running.
2019-06-14 23:18:04,650 - DEBUG - mpchc - file_info - Filepath F:\Present\JoJo's Bizarre Adventure - Golden Wind\[HorribleSubs] JoJo's Bizarre Adventure - Golden Wind - 34 [1080p].mkv
2019-06-14 23:18:04,651 - INFO - mpchc - file_info - File path not in whitelist.
2019-06-14 23:58:06,163 - INFO - mpchc - monitor - Unable to connect to mpchc. Ensure that the web interface is running.
2019-06-15 02:18:22,254 - DEBUG - mpchc - file_info - Filepath F:\Present\One Punch Man S2\[HorribleSubs] One Punch Man S2 - 09 [1080p].mkv
2019-06-15 02:18:22,255 - INFO - mpchc - file_info - File path not in whitelist.
2019-06-15 02:42:23,948 - INFO - mpchc - monitor - Unable to connect to mpchc. Ensure that the web interface is running.
2019-06-15 02:45:19,038 - DEBUG - mpchc - file_info - Filepath F:\Present\Carole & Tuesday\[PAS] Carole & Tuesday - 10 (WEB 720p AAC) [00D69AF8].mkv
2019-06-15 02:45:19,039 - INFO - mpchc - file_info - File path not in whitelist.
2019-06-15 03:07:00,664 - INFO - mpchc - monitor - Unable to connect to mpchc. Ensure that the web interface is running.
2019-06-15 03:12:07,775 - ERROR - mpchc - main - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\Fernando\AppData\Local\trakt-scrobbler\main.py", line 60, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "C:\Users\Fernando\AppData\Local\trakt-scrobbler\player_monitors\monitor.py", line 80, in run
    self.update_status()
  File "C:\Users\Fernando\AppData\Local\trakt-scrobbler\player_monitors\mpc.py", line 29, in update_status
    if variables['duration'] == '0':
KeyError: 'duration'
```
</p>
</details>

**Comment by iamkroot** [comment] 2019-06-16 07:00
Huh, that should definitely not be happening. If the player is stopped, it should automatically give a "Unable to connect" message, but here it seems that error is not being raised. I'm unable to reproduce this on my system either. Could you outline the exact steps that cause this bug? (A restart should be sufficient to reset the script)

**Comment by cyatek** [comment] 2019-06-16 14:08
I don't know what else to tell you, the steps are pretty much what's in the log. That day I watched only anime, which I use a different software to scrobble to a different site, next day say I wanna watch a Mad Men episode, the script will be dead. I don't do anything special at 03:12:07 the time of the crash, it just happens.

**Comment by iamkroot** [comment] 2019-06-17 04:18
> I use a pretty old version of MPC, 1.7.9.

Ah that might very well be the reason. I'll check what exactly the cause is.

**Comment by cyatek** [comment] 2019-06-17 12:08
MPC-HC 1.7.9

**Comment by iamkroot** [comment] 2019-06-23 13:21
Installed 1.7.9, but I'm still unable to reproduce the issue :/
Does this keep happening every time you restart?

**Comment by cyatek** [comment] 2019-06-23 17:32
It's been running no problem for a few days now so it's actually not caused by just leaving it on like I thought, something must've been the trigger, and I really don't remember anything I've done different from now. 
I'd say you should just forget about it for now and I'll get back to you whenever I figure it out what causes it :)

**Comment by iamkroot** [comment] 2019-06-24 04:30
Well okay then. Closing this for now. Feel free to reopen if it happens again, and we'll get to the bottom of it.

**Closed** 2019-06-24 04:30 UTC

**Comment by cyatek** [comment] 2019-06-30 09:12
Hey if you don't mind i dont really want to open another ticket since this is more of a personal problem i dont wanna clog it up.

So all of a sudden everything went to shit, when i click trakt-scrobbler.bat on the startup folder which is how i always started the script, it now prompts me with the "Open with:" screen as if python werent installed or something?
as i told you before i dont really know how to python but i tried some other ways to start it these being the results
https://i.gyazo.com/b611ae42884ab1a4260e45f4c41a92b2.png
https://i.gyazo.com/ff8a609a518154eccb7f719199ac40a1.png
(the toml file is untouched, everything is really, this started happening out of nowhere)

any idea what the fuck going on? tried reinstalling both the script and python with no changes

**Comment by iamkroot** [comment] 2019-07-01 13:46
As your edit suggests, there isn't any issue with the installation. This seems like a problem with how `.bat` files are handled on your system. Might be antivirus messing with how they are opened, or something else, can't really say.
