### ISSUE TITLE
Will not scrobble log says 404

### ISSUE THREAD

**Issue by CoLdAs1cE** [iamkroot/trakt-scrobbler#123] opened 2021-06-16 18:54 UTC
```
2021-06-16 20:46:53,091 - DEBUG - vlc - file_info - Guess: MatchesDict([('title', 'Hells Kitchen'), ('country', <Country [US]>), ('season', 20), ('episode', 2), ('screen_size', '1080p'), ('source', 'Web'), ('video_codec', 'H.264'), ('release_group', 'BAE[eztv.re]'), ('container', 'mkv'), ('mimetype', 'video/x-matroska'), ('type', 'episode')])
2021-06-16 20:46:53,091 - DEBUG - vlc - monitor - action=scrobble
2021-06-16 20:46:53,091 - DEBUG - vlc - monitor - {'state': 2, 'progress': 0.31, 'media_info': {'type': 'episode', 'title': 'Hells Kitchen', 'season': 20, 'episode': 2}, 'updated_at': 1623869213.0916605}
2021-06-16 20:46:53,091 - DEBUG - scrobbler - scrobbler - Scrobbling start at 0.31% for Hells Kitchen
2021-06-16 20:46:53,547 - WARNING - scrobbler - utils - Request failed
2021-06-16 20:46:53,547 - DEBUG - scrobbler - utils - Request: post {'url': 'https://api.trakt.tv/scrobble/start', 'headers': {'Content-Type': 'application/json', 'trakt-api-key': '', 'trakt-api-version': '2', 'Authorization': 'Bearer '}, 'json': {'show': {'ids': {'trakt': 13693}}, 'episode': {'season': 20, 'number': 2}, 'progress': 0.31}, 'timeout': 30}
2021-06-16 20:46:53,547 - DEBUG - scrobbler - utils - Response: <Response [404]> 
2021-06-16 20:46:53,547 - WARNING - scrobbler - trakt_interface - Not found on trakt. The media info is incorrect.
2021-06-16 20:46:53,547 - WARNING - scrobbler - scrobbler - Scrobble unsuccessful.
```

im not sure whats wrong

**Comment by iamkroot** [comment] 2021-06-17 13:54
The 404 means "Not Found", which almost always means some mistake in media info. In this case, you want to scrobble the show `Hell's Kitchen`, but looking at the failed request, the trakt id of your scrobbled show is `13693`, which is [Saturday Kitchen](https://trakt.tv/shows/saturday-kitchen). This doesn't have 20 seasons, so trakt is returning 404.

**Fix:** What you really want is the trakt id `2356`, which gives the correct page: [Hell's Kitchen](https://trakt.tv/shows/hell-s-kitchen-2005). You should update the entry in `trakt_cache.json` to this value. This file will be in your [data directory](https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#where-is-the-log-fileother-data-stored).

**How did I know the correct trakt id?** I'm querying the trakt api directly. I plan to expose this as a command in the future. See https://github.com/iamkroot/trakt-scrobbler/issues/95#issuecomment-751437087

**What can you do to prevent this?** The best way is to include the media year in the file path. This enables us to filter out most duplicates, since chances are very low that close-sounding shows were launched in the same year. (also notice that trakt name for this show is `hell-s-kitchen-2005`).

**What can I do to prevent this? (feel free to ignore, this is just me jotting stuff down so it doesn't get lost)** 
* One possible enhancement is that when deciding the trakt id for a media file, we could take into account its season and episode values. The extended query results include these values and we can crosscheck to make sure the season/episode actually exists. This would also need heavy caching, since the extended query request is very heavy (returns lots of info) and we want to minimize data transfers, which was the entire point of having `trakt_cache.json`.
* More immediately, I should probably add this info to the FAQ, after implementing `trakts lookup` decently well.

**Closed by iamkroot** 2021-06-17 13:54 UTC

**Comment by CoLdAs1cE** [comment] 2021-06-17 18:26
I got stumped pga. it worked fine for season 19 :O then it stopped working.

**Comment by iamkroot** [comment] 2021-06-18 04:13
The problem is the missing apostrophe. Searching `Hell's kitchen` gives the correct result, but `Hells kitchen` gives bad results. You may want to verify that the previous scrobbles have indeed gone to the right place. There will also probably be two (or more) entries in `trakt_cache.json` with and without the apostrophe.
