### ISSUE TITLE
[BUG] service crash during playing on Amazon Fire TV

### ISSUE THREAD

**Issue by Steefler35** [iamkroot/trakt-scrobbler#164] opened 2021-12-07 09:21 UTC
**Describe the bug**

The service crash during playing a media on Amazon Fire TV and not restart automatically.

**Desktop (please complete the following information):**
 - OS and Version: Ubuntu 20.04.3 LTS
 - Python Version: 3.8.10
 - Player and Version: Plex on Amazon Fire TV

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```
2021-12-02 17:27:27,112 - WARNING - scrobbler - scrobbler - Scrobble unsuccessful.
2021-12-02 21:19:58,789 - ERROR - plex - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/home/steven/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/__init__.py", line 42, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/home/steven/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/monitor.py", line 355, in run
    self.update_status()
  File "/home/steven/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/plex.py", line 88, in update_status
    status_data = self.get_data(self.session_url)
  File "/home/steven/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/trakt_scrobbler/player_monitors/plex.py", line 74, in get_data
    data = resp.json()["MediaContainer"]
  File "/home/steven/.local/pipx/venvs/trakt-scrobbler/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 13147 (char 13146)
```
</p>
</details>

**Comment by iamkroot** [comment] 2021-12-07 12:47
Looks like a duplicate of #161
This is a bug on Plex's side of things - they're sending malformed data to us.

**Closed** 2021-12-07 12:47 UTC
