### ISSUE TITLE
[BUG] Unhandled exception in MPC-HC monitor breaks scrobbler until restarted

### ISSUE THREAD

**Issue by visua0** [iamkroot/trakt-scrobbler#115] opened 2021-04-16 04:20 UTC
**Describe the bug**

I'm not sure what triggers it exactly, but about every other day the scrobbler completely dies on me until I stop and start it again.
The log shows a pretty obvious error:
```
ERROR - mpc-hc - __init__ - Unhandled exception
Traceback (most recent call last):
  File "[...]\trakt_scrobbler\__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 328, in run
    self.update_status()
  File "[...]\trakt_scrobbler\player_monitors\mpc.py", line 42, in update_status
    if variables['duration'] == '0':
KeyError: 'duration'
```
Annoyingly since the scrobbler is completely silent (or alternatively it spams you with notifications every time you pause and resume a video, which is even worse) it's impossible for me to tell it crashed until I just happen to check my history.

**Desktop (please complete the following information):**
 - OS and Version: Windows 10
 - Python Version: 3.8.0
 - Player and Version: MPC-HC 1.9.10

**To Reproduce**

1. Set up scrobbling for MPC-HC
2. Watch some episodes
3. Check your history on trakt.tv to see which episode you were on
4. Notice nothing has been scrobbled in the past couple of weeks
5. See error in log file
6. Try to remember what you watched and manually add it to your history

**Bonus suggestion**

Please make notifications usable by only showing them when you start and stop, not when you pause and resume.

**Comment by iamkroot** [comment] 2021-04-18 13:16
Thanks for creating the issue. There's multiple things to address here:
1. The `KeyError` is indeed weird. Could you please provide some of the previous lines from the log so I could try to reproduce the error? I mostly care about things like start/pause/stop events and their %ages in the log files.
2. I agree that the scrobbler should reliably notify the user in case some unhandled exception has occurred. Staying silent is not very good behaviour. I'll create a separate issue for this.
3. Originally, the user was notified only on start/stop scrobbles. I added the notifs on pause precisely as a fix for the above. If I don't see a notif on pause, I know something is wrong, and I can check the log file. Not a perfect solution, I know, and it's time to tackle it properly.
4. Regarding the bonus suggestion, that is also a bit non-trivial to implement. This is because there's no such thing as "resume" scrobble. Only start, pause and stop are valid. So I'll have to add more code to track the last scrobble and detect if it's a start or a resume. I prefer to avoid complexity, which is why this hasn't been implemented. But you are correct in saying that this should be a valid option for the user. I'll create another issue.

Again, thanks for the report!

**Comment by visua0** [comment] 2021-04-18 14:14
Thank you for taking my suggestions seriously.

Sorry, I should have provided more context for the log, even if I don't think it's relevant.
In both recent cases the error occurred while browsing through videos not in a whitelisted directory, so the most recent log line is about the previous video not being whitelisted. I don't think the whitelist is related, I think it's just a coincidence because I was opening, seeking through and closing a lot of files so it was more likely to happen then, but I can't say for sure.

~~If the error occurs while watching something whitelisted I'll let you know.~~
It just crashed on the very first episode I opened, and the log lines before the error are about a successful scrobble of the same show. I was going to try and crash it by rapidly going through a bunch of episodes, but it seems that is unrelated too. See the last log for this one.
Trying again with the same file does not cause the error again.

```
2021-04-16 00:06:23,572 - DEBUG - mpc-hc - file_info - Filepath '[...]'
2021-04-16 00:06:23,573 - INFO - mpc-hc - file_info - File path not in whitelist.
2021-04-16 00:06:48,654 - ERROR - mpc-hc - __init__ - Unhandled exception
Traceback (most recent call last):
  File "[...]\trakt_scrobbler\__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 328, in run
    self.update_status()
  File "[...]\trakt_scrobbler\player_monitors\mpc.py", line 42, in update_status
    if variables['duration'] == '0':
KeyError: 'duration'
```

```
2021-04-16 21:25:09,518 - DEBUG - mpc-hc - file_info - Filepath '[...]'
2021-04-16 21:25:09,519 - INFO - mpc-hc - file_info - File path not in whitelist.
2021-04-16 21:25:23,562 - INFO - mpc-hc - monitor - Unable to connect to mpc-hc. Ensure that the web interface is running.
2021-04-16 21:25:37,126 - ERROR - mpc-hc - __init__ - Unhandled exception
Traceback (most recent call last):
  File "[...]\trakt_scrobbler\__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 328, in run
    self.update_status()
  File "[...]\trakt_scrobbler\player_monitors\mpc.py", line 42, in update_status
    if variables['duration'] == '0':
KeyError: 'duration'
```

```
2021-04-18 04:33:12,315 - DEBUG - scrobbler - scrobbler - Scrobbling stop at 98.44% for [...]
2021-04-18 04:33:12,577 - INFO - scrobbler - scrobbler - Scrobble stop successful for [...]
2021-04-18 04:33:26,361 - INFO - mpc-hc - monitor - Unable to connect to mpc-hc. Ensure that the web interface is running.
2021-04-18 16:03:20,626 - ERROR - mpc-hc - __init__ - Unhandled exception
Traceback (most recent call last):
  File "[...]\site-packages\trakt_scrobbler\__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "[...]\site-packages\trakt_scrobbler\player_monitors\monitor.py", line 328, in run
    self.update_status()
  File "[...]\site-packages\trakt_scrobbler\player_monitors\mpc.py", line 42, in update_status
    if variables['duration'] == '0':
KeyError: 'duration'
```

**Comment by iamkroot** [comment] 2021-04-18 14:26
Hmm pretty weird. Another thing you can try is, you can open up your web browser to `localhost:13579/variables.html` whenever you're playing a file. When you see a crash in the scrobbler, refresh the page and see if "duration" is present there.

**Comment by visua0** [comment] 2021-04-18 14:53
I'll look at this next time it happens. Let me know if there's anything else you want me to try.

**Comment by visua0** [comment] 2021-04-18 17:47
Just ran into a different error. Don't think I've seen this one before.
I was browsing through some episodes to see if it would crash again, but then when I went from episode 5 to 6 it didn't log anything about 6, just a bunch of lines about preview, whatever that means. Then when I switched to yet another episode it crashed.

```
2021-04-18 19:33:38,926 - DEBUG - mpc-hc - file_info - Filepath '[...]\S08E05.mkv'
2021-04-18 19:33:38,954 - DEBUG - mpc-hc - file_info - Guess: MatchesDict([...])
2021-04-18 19:33:38,954 - DEBUG - mpc-hc - monitor - action=exit_preview
2021-04-18 19:33:38,954 - DEBUG - mpc-hc - monitor - Exiting preview
2021-04-18 19:33:38,954 - DEBUG - mpc-hc - monitor - action=enter_preview
2021-04-18 19:33:50,991 - DEBUG - mpc-hc - monitor - action=exit_preview
2021-04-18 19:33:50,991 - DEBUG - mpc-hc - monitor - Exiting preview
2021-04-18 19:33:50,992 - DEBUG - mpc-hc - monitor - action=enter_preview
2021-04-18 19:34:15,074 - DEBUG - mpc-hc - monitor - action=pause_preview
2021-04-18 19:34:27,110 - DEBUG - mpc-hc - monitor - action=exit_preview
2021-04-18 19:34:27,110 - DEBUG - mpc-hc - monitor - Exiting preview
2021-04-18 19:34:27,110 - ERROR - mpc-hc - __init__ - Unhandled exception
Traceback (most recent call last):
  File "[...]\trakt_scrobbler\__init__.py", line 32, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 340, in run
    self.handle_status_update()
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 310, in handle_status_update
    self.scrobble_if_state_changed(self.prev_state, current_state)
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 272, in scrobble_if_state_changed
    self.exit_preview()
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 248, in exit_preview
    self.clear_timer('preview_timer')
  File "[...]\trakt_scrobbler\player_monitors\monitor.py", line 240, in clear_timer
    timer.cancel()
  File "[...]\trakt_scrobbler\utils.py", line 132, in cancel
    self.timer.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
```

**Comment by iamkroot** [comment] 2021-04-18 17:56
Ah don't worry about that one. It's been fixed in the latest commit (https://github.com/iamkroot/trakt-scrobbler/commit/a02dc34406addfcfef963f0c0fa1be105ae4e15b), just that it hasn't been released yet. If you'd like to run this unreleased code, follow the instructions at https://github.com/iamkroot/trakt-scrobbler/wiki/Installation#installing-other-versions to install from master branch.

**Comment by iamkroot** [comment] 2021-04-23 09:23
I've pushed a new branch https://github.com/iamkroot/trakt-scrobbler/tree/mpchc-fix that adds some code to log some extra info when this bug occurs. Please install this using `pipx install --force git+https://github.com/iamkroot/trakt-scrobbler.git@mpchc-fix` and try restarting the scrobbler. Do note that you won't get the unhandled exception now, so you'll have to keep an eye on the log file continuously to spot this (it will print `Something weird happened: duration not found`)

**Comment by visua0** [comment] 2021-04-26 23:54
Okay, I managed to get the error again.
I closed MPC-HC between file1 and file2. The error happened the instant I opened file2, before MPC-HC had even loaded the file.
I'll try to trigger it again to see if that was just a crazy coincidence, but that would at least explain why `variables` was empty.

```
2021-04-27 01:36:14,619 - DEBUG - mpc-hc - file_info - Filepath 'file1'
2021-04-27 01:36:14,621 - INFO - mpc-hc - file_info - File path not in whitelist.
2021-04-27 01:36:52,715 - INFO - mpc-hc - monitor - Unable to connect to mpc-hc. Ensure that the web interface is running.
2021-04-27 01:37:19,736 - WARNING - mpc-hc - mpc - Something weird happened: duration not found
2021-04-27 01:37:19,736 - DEBUG - mpc-hc - mpc - Variables: {}
2021-04-27 01:37:31,768 - DEBUG - mpc-hc - file_info - Filepath 'file2'
2021-04-27 01:37:31,770 - INFO - mpc-hc - file_info - File path not in whitelist.
```

**Comment by iamkroot** [comment] 2021-04-28 02:59
So I guess we have identified the source of the bug. For some reason, when the file starts, MPC creates the variables page, but doesn't actually populate it until a few seconds later. But our scrobbler assumes that if the webpage is there, the variables are also present. Since this wasn't the case, we were crashing. The fix is to simply add another check that the necessary variables are present, since they will be captured during the next poll.

**Closed** 2021-04-28 03:07 UTC
Labels: bug, monitor

**Comment by visua0** [comment] 2021-04-28 13:22
Nice, thanks for the fix.
