### ISSUE TITLE
[BUG] `launchctl` errors in start/stop commands on MacOS

### ISSUE THREAD

**Issue by haykkh** [iamkroot/trakt-scrobbler#83] opened 2020-09-22 13:22 UTC
**Describe the bug**
1.1.0 doesn't seem to be working. I first upgraded from 1.0.0 using 

1. Stop the app using `trakts stop`
2. Run `pipx upgrade trakt-scrobbler`
3. Start the app again using `trakts start`

But `trakts start` gives 

```
$ trakts start
[CalledProcessError]
Command '['launchctl', 'start', 'com.iamkroot.trakt-scrobbler']' returned non-zero exit status 3.
```

`trakts status`:
```
$ trakts status
Could not find service "com.iamkroot.trakt-scrobbler" in domain for

[CalledProcessError]
Command '['launchctl', 'list', 'com.iamkroot.trakt-scrobbler']' returned non-zero exit status 113.
```

`trakts -V`:
```
$ trakts -V
Trakts version 1.0.0
```

According to `pipx list`:
```
$ pipx list
venvs are in /Users/me/.local/pipx/venvs
apps are exposed on your $PATH at /Users/me/.local/bin
   package trakt-scrobbler 1.1.0, Python 3.8.5
    - trakts
```

I have tried `pipx reinstall-all` / `pipx uninstall` + `pipx install` as well.

Running `trakts autostart enable` seems to have made it run, but it's still printing out 1.0.0 for `-V` and giving me the same errors as #82 when trying to clear backlogs.

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version: 3.8.5
 - Player: Plex
 - Player Version: 4.29.2

**Log file**
Log entries since update:
<details><summary>Click to see log contents</summary> 
<p>

```
2020-09-22 16:58:38,666 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 99.71, 'media_info': {'type': 'episode', 'title': 'The X-Files', 'season': '1', 'episode': 1}, 'updated_at': 1600518114.526402}
2020-09-22 16:58:39,293 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.65, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 3}, 'updated_at': 1600539429.3437939}
2020-09-22 16:58:39,722 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.69, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 4}, 'updated_at': 1600542651.411433}
2020-09-22 16:58:41,184 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.45, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 5}, 'updated_at': 1600547718.157074}
2020-09-22 16:58:41,852 - DEBUG - MainThread - backlog_cleaner - Adding item to history {'state': 2, 'progress': 96.17, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 6}, 'updated_at': 1600619220.821142}
2020-09-22 16:58:42,775 - INFO - MainThread - scrobbler - Started scrobbler thread.
2020-09-22 16:58:42,782 - INFO - MainThread - monitor - Started monitor for plex
2020-09-22 16:58:42,788 - DEBUG - scrobbler - scrobbler - Scrobbling pause at 78.19% for The X-Files
2020-09-22 16:58:43,278 - INFO - scrobbler - scrobbler - Scrobble pause successful for The X-Files S01E02
2020-09-22 16:58:44,614 - DEBUG - scrobbler - backlog_cleaner - Adding item to history {'state': 2, 'progress': 99.71, 'media_info': {'type': 'episode', 'title': 'The X-Files', 'season': '1', 'episode': 1}, 'updated_at': 1600518114.526402}
2020-09-22 16:58:45,334 - DEBUG - scrobbler - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.65, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 3}, 'updated_at': 1600539429.3437939}
2020-09-22 16:58:45,807 - DEBUG - scrobbler - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.69, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 4}, 'updated_at': 1600542651.411433}
2020-09-22 16:58:46,460 - DEBUG - scrobbler - backlog_cleaner - Adding item to history {'state': 2, 'progress': 95.45, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 5}, 'updated_at': 1600547718.157074}
2020-09-22 16:58:49,225 - DEBUG - scrobbler - backlog_cleaner - Adding item to history {'state': 2, 'progress': 96.17, 'media_info': {'type': 'episode', 'title': 'The Spy', 'season': '1', 'episode': 6}, 'updated_at': 1600619220.821142}

```
</p>
</details>

**Comment by iamkroot** [comment] 2020-09-22 14:12
> it's still printing out 1.0.0 for -V

**Comment by iamkroot** [comment] 2020-09-22 14:15
> it's still printing out 1.0.0 for `-`

That's my mistake. Forgot to update the value at one place! 

> same errors as #82 when trying to clear backlogs

Yeah, you'll have to manually edit `watched_backlog.json` file and remove the quotes, making `"1"` as `1` for all the season fields. Sorry for not clarifying this :sweat_smile:

**Comment by iamkroot** [comment] 2020-09-22 14:23
Although, I'm not sure why `trakts start` is failing after the update. Does it work after running `autostart enable`?

**Comment by haykkh** [comment] 2020-09-22 14:25
Thanks again!

```
$ trakts start
The scrobbler is running
Monitored players: plex
Last successful scrobble: Pause Raised by Wolves S01E04, at Tue Sep 22 17:48:56 2020
```

**Comment by iamkroot** [comment] 2020-09-22 14:27
Hmm weird indeed. I don't have access to a Mac so I can only guess the expected behaviour. We'll explore the bug if it happens again some time later.

**Comment by listy-bit** [comment] 2020-11-16 12:31
Hi, this has happened to me, but not after an update. It happened on the 11th, but I've only just noticed. I updated to latest version, but the issue was still present. Resolved by using `autostart enable`. Backlog was empty though, just `[]`.

MacOS
Python 3.8.5
Plex 1.20.4.3517
trakts 1.1.2 / 1.1.3

**Comment by iamkroot** [comment] 2020-11-21 10:50
This is mostly unrelated to the backlog cleaner, and has to do with the `launchctl` service manager on MacOS. Since I don't have access to a Mac, the current implementation is only based on what I could find on the net, and a few helpful users who tested some parts of it. I'd prefer if someone would take a proper look at getting to the root cause of this.

**Comment by Aerozolic** [comment] 2021-01-06 10:33
Yup, same problem here. macOS 10.15.7.
trakts status
Could not find service "com.iamkroot.trakt-scrobbler" in domain for port

[CalledProcessError]
Command '['launchctl', 'list', 'com.iamkroot.trakt-scrobbler']' returned non-zero exit status 113.

**Closed** 2021-09-22 02:19 UTC
Labels: bug, help wanted
