### ISSUE TITLE
[BUG] Unhandled exception

### ISSUE THREAD

**Issue by wazabees** [iamkroot/trakt-scrobbler#177] opened 2022-02-23 08:19 UTC
**Describe the bug**

trakt-scrobbler doesn't start when typing `trakts` and throws and error immediately.

**Desktop (please complete the following information):**
 - OS and Version: [e.g. Ubuntu 20.10]
 Arch Linux (5.16.10-arch1-1)

 - Python Version: [e.g. 3.7.3]
Python 3.10.2

 - Player and Version: [e.g. VLC v1.3.2]
mpv 0.34.1-dirty

**To Reproduce**

trakts does not start at all

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the next line completely-->
2022-02-23 08:56:52,183 - ERROR - MainThread - __init__ - Unhandled exception
Traceback (most recent call last):
  File "/usr/bin/trakts", line 33, in <module>
    sys.exit(load_entry_point('trakt-scrobbler==1.4.0', 'console_scripts', 'trakts')())
  File "/usr/bin/trakts", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/trakt_scrobbler/console.py", line 2, in <module>
    from cleo import Application
ImportError: cannot import name 'Application' from 'cleo' (/home/wazabees/.local/lib/python3.10/site-packages/cleo/__init__.py)
2022-02-23 08:56:52,184 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
```
</p>
</details>

**Comment by wazabees** [comment] 2022-02-23 18:08
I installed from AUR, yes - the git version.
https://aur.archlinux.org/packages/trakt-scrobbler-git

```
╭─   ~                                                                                                                                        19:06:34
╰─❯ python -c "from cleo import __version__; print(__version__)"
1.0.0a4
```

**Comment by iamkroot** [comment] 2022-02-23 18:38
I guess, all you need to do to fix it is install `python-cleo` and remove `python-cleo-git` from your system.

**Comment by wazabees** [comment] 2022-02-23 18:38
> I guess, all you need to do to fix it is install `python-cleo` and remove `python-cleo-git` from your system.

Yep - that solved it! Thanks so much. ;)

**Comment by iamkroot** [comment] 2022-02-23 18:40
@ahmubashshir Maybe you want to take a look at this? Do you know why it installed `python-cleo-git` even if it didn't meet the version requirements?

**Comment by wazabees** [comment] 2022-02-23 18:51
I'm pretty sure this wasn't because of traks-scrobbled, but another pypi package I installed for testing, called [`streamrip`](https://libraries.io/pypi/streamrip). It has cleo ==1.0.0a4 as a dependency.

**Comment by iamkroot** [comment] 2022-02-24 03:43
What package helper are you using? When I tried to repro this with `yay`, it automatically suggested that `python-cleo-git` isn't compatible and needs to be replaced with `python-cleo`.

**Comment by iamkroot** [comment] 2022-02-24 03:48
Ah, now I get it. You probably installed `streamrip` with `pip`, which means makepkg didn't know about `python-cleo-git`. Venvs are meant to solve this headache.

Closing this since the issue is resolved.

**Closed by iamkroot** 2022-02-24 03:48 UTC
Labels: setup
