### ISSUE TITLE
[Installation] stuck at trakts init

### ISSUE THREAD

**Issue by ymyogev** [iamkroot/trakt-scrobbler#262] opened 2023-11-11 20:35 UTC
### System Info
* Operating system and version: [Windows 11]
* Media Player and version: [irrelevant]
* Python version: [3.12..0]

### Description
I got a weird crash while trying to start the scrobbler using trakts init, after the installation was supposedly successful.
Would love assistance.
Thank you (-:

### Command line output

C:\Users\Administrator>trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  AttributeError

  module 'pkgutil' has no attribute 'ImpImporter'

  at .local\pipx\venvs\trakt-scrobbler\Lib\site-packages\pkg_resources\__init__.py:2191 in <module>
      2187│     dist_groups = map(find_distributions, resolved_paths)
      2188│     return next(dist_groups, ())
      2189│
      2190│
    → 2191│ register_finder(pkgutil.ImpImporter, find_on_path)
      2192│
      2193│ if hasattr(importlib_machinery, 'FileFinder'):
      2194│     register_finder(importlib_machinery.FileFinder, find_on_path)
      2195│

```

### Log file

<!--If the file doesn't exist, leave this section blank. -->

<!--
WARNING: The log file may contain passwords and other personally identifiable 
information like media file paths. If you are privacy-conscious (which you should be), 
only paste the relevant parts, and take care to redact out the personal info.
In case that info is required for fixing the issue, we can later discuss how to get it.
-->

<details>
  <summary>Click to see log contents</summary> <!--DO NOT REMOVE THIS LINE--> 
<p>

```<!--DO NOT REMOVE THE THREE BACKTICKS. Replace only the following lines between the three backticks (`)-->
(replace these lines) *PASTE LOG FILE CONTENTS HERE*
  Command: "trakts log open" or "trakts log path" or
  see [FAQ](https://github.com/iamkroot/trakt-scrobbler/wiki/FAQs#where-is-the-log-fileother-data-stored).
```
</p>
</details>

**Comment by iamkroot** [comment] 2023-11-20 00:06
Duplicate of #257. It has been fixed in master. Need to release a new version. Till then, you can follow the steps in https://github.com/iamkroot/trakt-scrobbler/issues/257#issuecomment-1752176431 to install the dev version

**Closed by iamkroot** 2023-11-20 00:06 UTC
