### ISSUE TITLE
[Installation] 

### ISSUE THREAD

**Issue by amphoterism** [iamkroot/trakt-scrobbler#233] opened 2022-12-21 05:39 UTC
### System Info
* Operating system and version: [Windows 11]
* Python version: [3.11]

### Description
Unable to install

### Command line output

```
PS C:\Users\rossn> trakts init
This will guide you through the setup of the scrobbler.
If you wish to quit at any point, press Ctrl+C or Cmd+C

  OSError

  [WinError -2147024809] The parameter is incorrect

  at AppData\Local\Programs\Python\Python311\Lib\site-packages\desktop_notifier\winrt.py:75 in __init__
       71│     ) -> None:
       72│         super().__init__(app_name, app_icon, notification_limit)
       73│         self._appid = CoreApplication.get_id()
       74│         self.manager = ToastNotificationManager.get_default()
    →  75│         self.notifier = self.manager.create_toast_notifier(self._appid)
       76│
       77│     async def request_authorisation(self) -> bool:
       78│
       79│         Request authorisation to send notifications.
```

### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```2022-12-20 21:17:24,295 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2022-12-20 21:33:31,329 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt

```
</p>
</details>

**Comment by iamkroot** [comment] 2022-12-26 03:40
Duplicate of #224

**Closed by iamkroot** 2022-12-26 03:40 UTC
