### ISSUE TITLE
Can't find config or log file

### ISSUE THREAD

**Issue by ang3lo-azevedo** [iamkroot/trakt-scrobbler#196] opened 2022-07-04 10:04 UTC
**Describe the bug**

I can't find the .yaml or the .log files, they're not on the supposed location.

**Desktop (please complete the following information):**
 - Windows 11
 - 3.10
 - mpv.net

**Comment by the-nos4a2** [comment] 2022-07-06 19:01
![image](https://user-images.githubusercontent.com/66081804/177623502-484cb578-ad10-43c6-a60f-696378fda92d.png)

It says this, but there is nothing in that path

**Comment by iamkroot** [comment] 2022-07-07 03:11
Have you run `trakts init` fully?

**Comment by the-nos4a2** [comment] 2022-07-07 09:17
> Have you run `trakts init` fully? 

Yes, but I will try to run it again

**Comment by panaris** [comment] 2022-07-26 13:28
I have the same problem too.

**Comment by panaris** [comment] 2022-08-02 23:58
there is no folder named "trakt-scrobbler" in AppData/Roaming

**Comment by iamkroot** [comment] 2022-11-26 09:24
@panaris do you still have the issue?

**Comment by panaris** [comment] 2022-11-28 13:08
yes. just installed fresh windows 11 latest, with latest latest trakt scrobbler 1.6.1-beta1 and I confirm that there is not such path created.

**Comment by th3guard1an** [comment] 2023-02-20 05:44
I am having the same problem. Windows 11 PRO N. Python 3.10.10, pip 23.0.1, VLC. Followed the instalation guide with no errors.
Ran "\trakts init" and setup 1 player, and 3 whitelisted locations. 
Althought there is no folder in %appdata%/roaming/, restarting and shuting down doesn't reset the settings. 
Running "\trakts config list" and "\trakts test vlc", while playing media will still works properly and as espected.
I have had vlc running for a while, and there is no syncing with trakts.tv. 
Also, "\trakts backlog" list gives always an empty result.
I've reinstalled trakts,python, and vlc with the same outcome.

As anyone found a solution? Thank you.

**Comment by iamkroot** [comment] 2023-02-21 02:46
@th3guard1an Does `trakts log open` work? What path does it print?

**Comment by panaris** [comment] 2023-02-21 23:00
It prints

Log file is located at: "C:\Users\panar\AppData\Roaming\trakt-scrobbler\trakt_scrobbler.log"
In case this command doesn't work, manually open the log file from the path.

and it opens the Documents folder.

**Comment by iamkroot** [comment] 2023-02-25 02:56
What happens when you open Run (press Windows+R) and type `%AppData%` in it?

**Comment by panaris** [comment] 2023-02-28 13:22
correctly opens C:\Users\panar\AppData\Roaming

**Comment by iamkroot** [comment] 2023-02-28 15:47
And there is no `trakt-scrobbler` folder inside it?

**Comment by panaris** [comment] 2023-03-14 12:05
sorry for the late reply, but no.

**Comment by th3guard1an** [comment] 2023-03-14 21:59
@iamkroot > @th3guard1an Does `trakts log open` work? What path does it print?

"trakts log open" printed the expected path in "C:\Users\jpdr\AppData\Roaming\trakt-scrobbler\trakt_scrobbler.log" but opened the Default "Documents" Folder in Windows.
As said by panaris, the folder is simply not present in the appdata folder, not in roaming, not in local, nor locallow (I searched all of these before submiting the earlier reply).
I installed it on my windows 11 PRO N laptop and it created a folder as expected. I can't really tell why it isn't creating the folder on my Desktop, even after several tries at reinstalling. If I do a clean install in the future I will give an update.
Sorry for answering so late, thx for your time.

**Comment by iamkroot** [comment] 2023-03-17 03:31
This is very weird indeed.
Maybe we can try to create the folder manually and see what happens:
1. Open Powershell
2. (Assuming you installed using pipx) Enter `C:\Users\<Your Username>\.local\pipx\venvs\trakt-scrobbler\bin\Activate.ps1`. This should activate the python environment of this app.
3. Run `python`. Now you are in the python repl (it should show `>>>` as the prompt)
4. `from trakt_scrobbler.app_dirs import DATA_DIR, CFG_DIR`
5. `print(DATA_DIR)`
6. `assert DATA_DIR == CFG_DIR`
7. `DATA_DIR.exists()`
If it says `True`, then we are in big trouble :P
But if the above says `False`, try-
8. `DATA_DIR.mkdir()`
9. And again `DATA_DIR.exists()`

And report back

**Comment by panaris** [comment] 2023-03-19 21:21
https://bit.ly/3FwFEZO

**Comment by th3guard1an** [comment] 2023-03-19 23:48
![Untitled](https://user-images.githubusercontent.com/82462347/226217375-ae0fc6ac-8b6e-44c6-868a-e021c773350d.png)

Well, it does indicate "True" which is a bummer. Just to make sure, I sent a screenshot of my roaming folder, and as u can see, there is no "trakt-scrobbler".

**Comment by iamkroot** [comment] 2023-03-21 01:45
I'm seeing that both of you needed to use the Administrator privileges to run the commands. Any particular reason for that? It is supposed to work just fine as normal user.

**Comment by iamkroot** [comment] 2023-03-21 01:49
Also, how did you install python?

This might the the cause: https://stackoverflow.com/a/62095380

**Comment by th3guard1an** [comment] 2023-03-21 02:46
The commands can be ran without admin priveledge (just tested), I just so happen to have an admin console open.
I've tried several diferent versions of python, firstly throught winget (not MS), then manual website download, currently I'm on MS STORE install. Following the indications on your link I was able to find the missing folder under:
 "C:\Users\jpedr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Roaming"

My original problem was that the script wasn't syncing into trakts website, should I start a new thread with the newfound "logs", or do you think it might be related to this pathing problem? Thank you

**Comment by iamkroot** [comment] 2023-03-21 14:42
> I was able to find the missing folder

Finally some progress! Pinging @panaris @ang3lo-azevedo this might be the solution for you too.

I didn't expect Store apps to be doing this kind of shady stuff :( They seem to be hijacking the paths. https://learn.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data

We really need to provide a standard way of installing trakt-scrobbler on windows, preferably with its own bundled Python. #244 

> My original problem was that the script wasn't syncing into trakts website, should I start a new thread with the newfound "logs", or do you think it might be related to this pathing problem?

From what I can tell by reading the docs of msft, it seems that this new path should be "seamless" as far as the app is concerned (hence the `DATA_DIR.exists() == True` inside the console). I suggest going through the logs once and trying to see where the error is. If that doesn't work out, feel free to create a separate issue with the logs :)

**Comment by iamkroot** [comment] 2023-10-08 22:12
Will close this for now. If anyone is facing this, first give https://github.com/iamkroot/trakt-scrobbler/issues/196#issuecomment-1477206537 a shot. If that doesn't work, create a new issue.

**Closed by iamkroot** 2023-10-08 22:12 UTC
Labels: setup, needs-more-info
